# Generated by Django 6.0.4 on 2026-05-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Anonim Paylaş'),
        ),
        migrations.AlterField(
            model_name='post',
            name='addiction_type',
            field=models.CharField(choices=[('smoking', 'Sigara'), ('alcohol', 'Alkol'), ('gaming', 'Oyun'), ('screen_time', 'Ekran Süresi'), ('madde', 'Madde'), ('general', 'Genel')], default='general', max_length=20, verbose_name='Kategori'),
        ),
    ]
