# Generated by Django 6.0.4 on 2026-05-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_post_is_anonymous_alter_post_addiction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='addiction_type',
            field=models.CharField(choices=[('ekran', 'Ekran Bağımlılığı'), ('sigara', 'Sigara Bağımlılığı'), ('alkol', 'Alkol Bağımlılığı'), ('madde', 'Madde Bağımlılığı')], default='ekran', max_length=20, verbose_name='Kategori'),
        ),
    ]
