# Generated by Django 6.0.4 on 2026-04-29 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DependencyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('sigara', 'Sigara'), ('alkol', 'Alkol'), ('ekran', 'Ekran'), ('madde', 'Madde')], max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('initial_score', models.IntegerField(help_text='Kayıt anketinden gelen başlangıç skoru (0-100)')),
                ('target_note', models.TextField(blank=True, help_text='Kullanıcının kendine koyduğu motivasyon sözü')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('craving_level', models.IntegerField(help_text='1-10 arası zorlanma/istek seviyesi')),
                ('relapse', models.BooleanField(default=False, help_text='Bugün kural bozuldu mu?')),
                ('trigger', models.CharField(blank=True, help_text='Tetikleyici unsur', max_length=100)),
                ('daily_note', models.TextField(blank=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tracking.dependencygoal')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
