# Generated by Django 6.0.4 on 2026-05-02 22:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
