# Generated by Django 6.0.4 on 2026-05-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_dailylog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencygoal',
            name='bio',
            field=models.TextField(blank=True, help_text='Yol arkadaşlarınıza kendinizden ve motivasyonunuzdan bahsedin.', max_length=500),
        ),
    ]
