# Generated by Django 6.0.4 on 2026-05-03 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_dependencygoal_bio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Rozetin bilimsel veya motivasyonel açıklaması')),
                ('image_name', models.CharField(help_text='İkon için emoji veya dosya adı (örn: 🛡️)', max_length=50)),
                ('days_required', models.IntegerField(help_text='Bu rozeti almak için gereken kesintisiz gün sayısı')),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kazanılan Rozet',
                'verbose_name_plural': 'Kazanılan Rozetler',
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
